### PR TITLE
Modularize everything (for real this time)

### PR DESCRIPTION
**Pull request by RauliL**
Turn `jkiss.js` and `engine.js` into real JavaScript modules and use Webpack to bundle debug user interface. (Previously known as default theme.)

Name of the branch was inspired by this song, which is incidentally exactly what I feel about JavaScript and Webpack:
[Whitney Houston - It's Not Right But It's Okay](https://www.youtube.com/watch?v=6J538b-OLRU)

### CODE REVIEW

**Comment by frostburn** [comment]
Could you add a line or two in the readme about how to build and use this project now?

**Comment by RauliL** [comment]
The main engine is not built in any way, the debugging user interface is. I will add readme to it's directory.

**Comment by frostburn** [comment]
There are some issues with `npm run watch` on Chrome that should be resolved.

**Comment by frostburn** [comment]
Seems to work now in Chrome with `build` and `watch`. The code looks good. Merge at will.

**Pull request merged**
