### PR TITLE
Use ESLint to fix errors and warnings in the entire project

### PR DESCRIPTION
**Pull request by RauliL**
ESLint reported many errors and oddities that need to be fixed. Does not attempt to repair the API design itself.

### CODE REVIEW

**Comment by frostburn** [comment]
The `NEVER AGAIN` comments should be converted to something searchable with a clearer description of what is wrong.

**Comment by RauliL** [comment]
Did that.

**Comment by frostburn** [comment]
Why is there a merge commit when a rebase is more clean?

**Comment by frostburn** [comment]
There goes `npm run watch` support for Chrome... Oh well.

**Comment by frostburn** [comment]
Breaks SVG.js.

**Comment by RauliL** [comment]
GitHub created the commit when I decided to try the new feature which allows you to fix merge conflicts directly from the browser. Need to test more on this though how it suddenly breaks stuff.

**Comment by RauliL** [comment]
Closing as unnecessary bullshit.

**Pull request closed without merging**
